# Generated by Django 5.1.2 on 2024-11-24 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('heigth', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('eyes', models.CharField(max_length=16)),
                ('skin', models.CharField(max_length=32)),
                ('hair', models.CharField(max_length=64)),
                ('allies_and_orgs', models.TextField()),
                ('apperance', models.TextField()),
                ('backstory', models.TextField()),
                ('treasure', models.TextField()),
                ('additionalFeaturesAndTraits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CasterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spellcastingClass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.class')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('experience', models.IntegerField(default=0)),
                ('deathSaveSuccess', models.IntegerField(default=0)),
                ('deathSaveFailure', models.IntegerField(default=0)),
                ('temporaryHitpoint', models.IntegerField(default=0)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.alignment')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.background')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('caster_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.casterinfo')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classname', to='library.class')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.race')),
                ('info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.characterinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.IntegerField()),
                ('sp', models.IntegerField()),
                ('ep', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.item')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.BooleanField(default=False)),
                ('expertise', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSpells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.spell')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='SpellSlotsExpended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('count', models.IntegerField()),
                ('spellCasterInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.casterinfo')),
            ],
        ),
    ]
