# Generated by Django 5.1.2 on 2024-11-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='campaign',
        ),
    ]
