# Generated by Django 5.1.2 on 2024-11-26 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_character_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterequipment',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='characterspells',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='characterstatistic',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='characters.character'),
        ),
    ]
