# Generated by Django 5.1.2 on 2024-11-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_characterequipment_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='character',
            name='background',
        ),
        migrations.RemoveField(
            model_name='character',
            name='caster_info',
        ),
        migrations.RemoveField(
            model_name='character',
            name='deathSaveFailure',
        ),
        migrations.RemoveField(
            model_name='character',
            name='deathSaveSuccess',
        ),
        migrations.RemoveField(
            model_name='character',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='character',
            name='info',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='temporaryHitpoint',
        ),
    ]
