# Generated by Django 5.1.2 on 2024-12-02 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_remove_character_alignment_and_more'),
        ('library', '0002_alignment_created_by_background_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='classname',
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NewCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('experience', models.IntegerField(default=0)),
                ('deathSaveSuccess', models.IntegerField(default=0)),
                ('deathSaveFailure', models.IntegerField(default=0)),
                ('temporaryHitpoint', models.IntegerField(default=0)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.alignment')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.background')),
                ('caster_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.casterinfo')),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classname', to='library.class')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='characters.characterinfo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.race')),
            ],
        ),
    ]
