# Generated by Django 5.1.2 on 2024-10-15 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='statisctics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statistics', to='main.statisctics'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
