# Generated by Django 5.1.2 on 2024-11-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_character_experience_alter_character_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casterinfo',
            old_name='spellcasting_class',
            new_name='spellcastingClass',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='death_save_failure',
            new_name='deathSaveFailure',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='death_save_success',
            new_name='deathSaveSuccess',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='temporary_hitpoint',
            new_name='temporaryHitpoint',
        ),
        migrations.RenameField(
            model_name='characterinfo',
            old_name='additional_features_and_traits',
            new_name='additionalFeaturesAndTraits',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='spellcasting_ability',
            new_name='spellcastingAbility',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='attack_bonus',
            new_name='attackBonus',
        ),
        migrations.RenameField(
            model_name='spellslotsexpended',
            old_name='spell_caster_info',
            new_name='spellCasterInfo',
        ),
    ]
