# Generated by Django 5.1.2 on 2024-10-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_character_statisctics_alter_class_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statisctics',
            new_name='Statistics',
        ),
    ]
