# Generated by Django 5.1.2 on 2024-11-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_spellcasting_class_casterinfo_spellcastingclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.CharField(default='Touch', max_length=256),
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.CharField(default='', max_length=64),
        ),
    ]
