# Generated by Django 5.1.2 on 2024-10-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_statistics_charisma_statistics_constitution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='statisctics',
            new_name='statistics',
        ),
    ]
