# Generated by Django 5.1.2 on 2024-12-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignchatmessage_created_at'),
        ('characters', '0007_rename_apperance_characterinfo_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignplayer',
            name='character',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.newcharacter'),
        ),
    ]
