# Generated by Django 5.1.2 on 2024-11-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignchatmessage_created_at'),
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='campaigns.campaign')),
            ],
        ),
        migrations.AlterField(
            model_name='combatsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_sessions.campaignsession'),
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaignplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game_sessions.campaignsession')),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
