# Generated by Django 5.1.2 on 2024-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0002_campaignsession_alter_combatsession_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsession',
            name='ended_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
