# Generated by Django 5.1.2 on 2024-12-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0004_campaignsession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsession',
            name='token',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
