# Generated by Django 5.1.2 on 2024-12-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaignplayer_character'),
        ('game_sessions', '0005_alter_campaignsession_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSessionConnectedPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_sessions', to='campaigns.campaignplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_players', to='game_sessions.campaignsession')),
            ],
        ),
    ]
